# fly.toml app configuration file generated for wine-pick on 2023-12-17T01:09:56+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wine-pick"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[regions]
  name = "yyz"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

